name: App

on:
  push:
    branches:
      - master

jobs:
  publish_to_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build docker image
        id: prep
        run: |
          docker build -t ${DOCKER_IMAGE}:$(git rev-parse --short HEAD) -f app/Dockerfile .
          docker push ${DOCKER_IMAGE}:$(git rev-parse --short HEAD)
          TAG=$(git rev-parse --short HEAD)
          echo ::set-output name=tag::${TAG}
        env:
          DOCKER_IMAGE: raghukiran/app
     

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'values.yaml'
          propertyPath: 'image.tag'
          value: $(git rev-parse --short HEAD)
          branch: charts
          targetBranch: master
          createPR: true
          message: 'Bump docker Image Version to ${{ steps.prep.outputs.tag }} for admin portal'
