name: App

on:
  push:
    branches:
      - master

jobs:
  publish_to_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/app
          VERSION=$(git rev-parse --short HEAD)
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}


      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
        
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and analyze
        run: |
          pwd
          mkdir -p app/publish
          touch app/publish/testfile
          ls -la
          tree .

      - name: Check contents
        run: |
          pwd
          tree
          ls -la
      
      - name: Login and build
        run: |
          echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USER} --password-stdin docker.io
          cd app && docker build . --file Dockerfile --tag ${DOCKER_IMAGE}:${TAGS}
          docker push ${DOCKER_IMAGE}:${DOCKER_IMAGE}
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
     

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.prep.outputs.version }}
          targetBranch: development
          message: 'Bump docker Image Version to ${{ steps.prep.outputs.version }} for app service' 
