name: AccountEngine

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: web/admin_portal/Dockerfile-dev
          push: true
          tags: user/app:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
