name: AccountEngine

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'services/account_engine'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'services/account_engine'
    branches:
      - master
      - develop
      - feature/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Restore dependencies
        run: dotnet restore services/account_engine/Api

      - name: Build
        run: dotnet build --no-restore services/account_engine/Api
